name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"  # todos los días a medianoche
  workflow_dispatch:     # permite ejecución manual

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Archivo generado
          filename: metrics.svg

          # Tokens necesarios
          token: ${{ secrets.METRICS_TOKEN }}
          config_stargazers_token: ${{ secrets.MAPS_API_KEY }}

          # Datos base
          base: header, activity, community, repositories, metadata

          # Plugins activados
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_calendar: yes
          plugin_calendar_limit: 1
          plugin_stargazers: yes
          plugin_stargazers_worldmap: yes
          plugin_terminal: yes
          plugin_xkcd: yes
          plugin_website: yes
          plugin_website_url: https://github.com/marichu-kt
