name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: '0 18 * * *'  # Se ejecuta diariamente a las 18:00 UTC
  workflow_dispatch:       # Permite ejecución manual desde la pestaña Actions

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D Contributions
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate GitHub Profile 3D
        uses: yoshi389111/github-profile-3d-contrib@0.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # ✅ NO lo creas tú, ya existe

      - name: Commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "🧱 Update 3D profile contributions"
          git push
