name: Actualizar cache_bust y timestamp en README

on:
  schedule:
    - cron: '0 2 * * *'  # Ejecutar todos los días a las 02:00 UTC
  workflow_dispatch:      # Permitir ejecución manual desde GitHub

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Git
        run: |
          git config user.name "marichu-kt"
          git config user.email "marichu-kt@users.noreply.github.com"

      - name: Actualizar README.md
        run: |
          FECHA=$(date -u '+%Y%m%d')
          TIMESTAMP=$(date -u '+%Y-%m-%d %H:%M:%S UTC')

          echo "🛠️ cache_bust = $FECHA"
          echo "🛠️ timestamp = $TIMESTAMP"

          # 1. Actualizar la primera línea del README.md con la fecha y hora actuales
          sed -i "1s|^.*$|<!-- Última actualización: $TIMESTAMP -->|" README.md

          # 2. Eliminar cualquier cache_bust anterior
          sed -i 's/&cache_bust=[0-9]\{8\}//g' README.md

          # 3. Añadir nuevo cache_bust justo antes del cierre de la comilla en cada src=""
          sed -i -E 's|(src="[^"]+)(\")|\1\&cache_bust='"$FECHA"'\2|g' README.md

      - name: Confirmar cambios si los hay
        run: |
          if git diff --quiet; then
            echo "No hay cambios que guardar."
            exit 0
          fi

          git add README.md
          git commit -m "cache_bust actualizado a $FECHA"
          git push
